### ISSUE TITLE
Minor typos in Ch02

### ISSUE THREAD

**Issue by rdeits** [BenLauwens/ThinkJulia.jl#1]
I just started looking at the ThinkJulia book. It looks really nice--thanks for putting this together! 

Just a couple things I noticed: 

* In the second paragraph of https://benlauwens.github.io/ThinkJulia.jl/latest/chap02.html#Variable-names-1 "variables names" should be "variable names". 
* In the code block below, there should be an error message after `more@ = 100000` but instead `type = "Advanced Theoretical Zymurgy"` is written twice.

**Comment by BenLauwens** [comment]
Thanks!
