### ISSUE TITLE
 'add ThinkJulia' doesn't work in Julia 1.0

### ISSUE THREAD

**Issue by olejorik** [BenLauwens/ThinkJulia.jl#10]
Section 4, just in the beginning.

**Comment by olejorik** [comment]
should be changed to "add https://github.com/BenLauwens/ThinkJulia.jl", to my understanding

**Comment by BenLauwens** [comment]
Good point! I will change this. I do not expect that ThinkJulia will be accepted as a real package. I will push some more corrections to Github!
