### ISSUE TITLE
Exercise 3-3 renders incorrectly

### ISSUE THREAD

**Issue by aaronang** [BenLauwens/ThinkJulia.jl#12]
[Exercise 3-3](https://benlauwens.github.io/ThinkJulia.jl/latest/book.html#ex03-3) renders incorrectly as shown in the image below.

![image](https://user-images.githubusercontent.com/7579804/46262712-fac4de80-c4b9-11e8-9293-091da2191f19.png)

This happens in Google Chrome Version 69.0.3497.100 (Official Build) (64-bit).

**Comment by BenLauwens** [comment]
Thanks! Another index error;)
