### ISSUE TITLE
Incorrect rendering in "Nested Conditionals"

### ISSUE THREAD

**Issue by aaronang** [BenLauwens/ThinkJulia.jl#14]
In the section "Nested Conditionals", there is some text that doesn't render correctly, see [`(((indentation)`](https://github.com/BenLauwens/ThinkJulia.jl/blob/master/book/src/chap05.asciidoc#nested-conditionals).

**Comment by BenLauwens** [comment]
Thanks! I will push a bug of corrections to GitHub.
