### ISSUE TITLE
PDF or ePub format release

### ISSUE THREAD

**Issue by bthallplz** [BenLauwens/ThinkJulia.jl#16]
Hello, are there any plans to release this book in a PDF or ePub format? Such formats would make it easier for me, at least, to read it, especially when I happen to be offline.

**Comment by BenLauwens** [comment]
The book will be published in May by O'reilly. I cannot put a pdf version online.
The transformation from AsciiDoc to PDF is possible with [https://github.com/asciidoctor/asciidoctor-pdf](https://github.com/asciidoctor/asciidoctor-pdf).
