### ISSUE TITLE
Maybe add syntax highlighting

### ISSUE THREAD

**Issue by kramred** [BenLauwens/ThinkJulia.jl#3]
Hello,

great idea making this book for Julia.
I thinks the legibility of the code blocks would increase a lot with `syntax highlighting`:
For the HTML version one could use e.g. [Prism](https://prismjs.com/)
Although their Julia is not up to date...
Or whatever Github uses for syntax highlighting (apparently it's [Linuist](https://github.com/github/linguist))
More highlighters: https://github.com/JuliaEditorSupport/3rd-Party-Highlighters

E.g.
```
function fib(n)
    if n == 0
        return 0
    elseif n == 1
        return 1
    else
        return fib(n-1) + fib(n-2)
    end
end
```

versus:
```julia
function fib(n)
    if n == 0
        return 0
    elseif n == 1
        return 1
    else
        return fib(n-1) + fib(n-2)
    end
end
```

Anyway, what do you think about adding syntax highlighting for the code blocks?

**Comment by BenLauwens** [comment]
Consider it done;)
I have used pygments because it is integrated in ASCIIDoctor.
