### ISSUE TITLE
"Package ThinkJulia does not have Libdl in its dependencies" shown when adding ThinkJulia

### ISSUE THREAD

**Issue by Talinx** [BenLauwens/ThinkJulia.jl#37]
When adding ThinkJulia (with `add https://github.com/BenLauwens/ThinkJulia.jl`) the following warning is shown:
`┌ Warning: Package ThinkJulia does not have Libdl in its dependencies:`  
`│ - If you have ThinkJulia checked out for development and have`
`│   added Libdl as a dependency but haven't updated your primary`
``│   environment's manifest file, try `Pkg.resolve()`.``
`│ - Otherwise you may need to report an issue with ThinkJulia`
`└ Loading Libdl into ThinkJulia from project dependency, future warnings for ThinkJulia are suppressed.`

I used julia version 1.3.1 on Linux.

**Comment by BenLauwens** [comment]
Should be solved now
