### ISSUE TITLE
Transitioning from REQUIRE to Project.toml needed

### ISSUE THREAD

**Issue by anemochore** [BenLauwens/ThinkJulia.jl#39]
Since v1.4, 'add https://github.com/BenLauwens/ThinkJulia.jl' does not work. 
According to [this issue](https://github.com/JuliaLang/Pkg.jl/issues/1648), `REQUIRE` should be replace to `Project.toml`.

**Comment by ghost** [comment]
I've encountered the same problem. Trying to install on v1.4.0 on Windows 10 Pro 64-bit, downloaded from julialang.org. Unable to add, so Chapter 4 is a read-only chapter.

**Comment by BenLauwens** [comment]
Done!

**Comment by ghost** [comment]
Thank you! And thank you for writing your very useful book.
