### ISSUE TITLE
ERROR: cannot assign variable MathConstants.π from module Main

### ISSUE THREAD

**Issue by aaronang** [BenLauwens/ThinkJulia.jl#8]
In the section ["Assignment Statements"](https://github.com/BenLauwens/ThinkJulia.jl/blob/master/book/src/chap02.asciidoc#assignment-statements), `π` is assigned but when following along in the REPL, it gives the following error message:

```console
julia> π = 3.14
ERROR: cannot assign variable MathConstants.π from module Main
Stacktrace:
 [1] top-level scope at none:0
```

I assume this used to be valid before Julia 1.0?

Thank you for this wonderful book 🙇👏

**Comment by BenLauwens** [comment]
Thanks!
π is already defined.
I can not reproduce this problem in Julia v1.0.0 and v1.0.1.
I  changed the name to `πval` to avoid the problem.

**Comment by aaronang** [comment]
I see! You can reproduce it this way:

```julia
julia> π
π = 3.1415926535897...

julia> π = 3.14
ERROR: cannot assign variable MathConstants.π from module Main
Stacktrace:
 [1] top-level scope at none:0
```
