### ISSUE TITLE
ERROR: cannot assign variable Base.first from module Main

### ISSUE THREAD

**Issue by aaronang** [BenLauwens/ThinkJulia.jl#9]
In the section ["String Operations"](https://github.com/BenLauwens/ThinkJulia.jl/blob/master/book/src/chap02.asciidoc#string-operations), `first` cannot be assigned.

```console
julia> first = "throat"
ERROR: cannot assign variable Base.first from module Main
Stacktrace:
 [1] top-level scope at none:0
```

**Comment by BenLauwens** [comment]
I can not reproduce your error. But I think it is linked to the function Base.first. I have changed the name of the strings to `first_str` and `second_str` to be sure that this problem is avoided
